# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealOrdering', '0007_auto_20160410_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.DecimalField(blank=True, decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.DecimalField(blank=True, decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='positionforrest',
            name='belonging',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expire',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='PositionForRest',
        ),
        migrations.AddField(
            model_name='restaurantaddress',
            name='belonging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealOrdering.Restaurant'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='belonging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealOrdering.Customer'),
        ),
    ]
