# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealOrdering', '0008_auto_20160414_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionforuser',
            name='belonging',
        ),
        migrations.DeleteModel(
            name='PositionForUser',
        ),
    ]
