# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealOrdering', '0012_auto_20160415_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholeMoney', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('createTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('belonging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealOrdering.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expire',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='zipcode',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='belonging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_customer', to='MealOrdering.Customer'),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_dish', to='MealOrdering.Dish'),
        ),
        migrations.AlterField(
            model_name='restaurantaddress',
            name='zipcode',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='wholeorder',
            name='dishes',
            field=models.ManyToManyField(to='MealOrdering.DishHistory'),
        ),
    ]
